/*Copyright (C) 2022-2026 Crawford Currie https://github.com/cdot
  License MIT. See README.md at the root of this distribution for full copyright
  and license information.*/

// Placeholder key construction. Mixed unicode scripts are used to
// minimise risk of collision with real key names.
const SECRET = "ആଈ£";
const PLACEHOLDRE = new RegExp(`^${SECRET}(.+)$`);

// Key used when a datum has already been processed - removed after
// key remapping. Mixed unicode scripts are used to minimise risk of
// collision with real key names.
const PROCESSED = "ρѓσςεรຂεϑ";

// Private CBOR tag ID
// see https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml
const CBOR_KEY_MAP = 25446;

/**
 * Locate uses of key placeholders in data and replace them with
 * the real key.
 * @private
 */
function remapKeys(data, i2k) {
  const processed = [];

  function _remapKeys(data) {
    if (typeof data === "object" && data !== null) {
      if (Array.isArray(data)) {
        for (const d of data)
          _remapKeys(d);
        return;
      }
      if (data[PROCESSED]) return;
      processed.push(data);
      data[PROCESSED] = true;
      const phKeys = Object.keys(data);
      for (const ph of phKeys) {
        _remapKeys(data[ph]);
        const m = PLACEHOLDRE.exec(ph);
        if (m) {
          data[i2k[m[1]]] = data[ph];
          delete data[ph];
        }
      }
    }
  }
  _remapKeys(data);
  // clean up
  for (const p of processed)
    delete p[PROCESSED];
}

/**
 * TagHandler mixin.
 * To reduce data volume, use a key dictionary (a list of all known
 * keys used in JS objects). This can save a lot of space when a lot
 * of similar objects are used.
 * @mixin KeyDictionaryHandler
 */
const KeyDictionaryHandler = superclass => class extends superclass {

  /**
   * The same parameters have to be provided to the tag handlers
   * at both ends of the communication.
   * @param {string[]} options.keys list of known keys for the key.
   * Minimum output size will be achieved when this list is complete
   * i.e. all possible keys are known in advance.
   * @param {function?} options.added optional function called when an
   * unknown key is added to the key set. Passed the key and the id it was
   * assigned. This can be useful when building a comprehensive key set
   * for communication in complex code.
   */
  constructor(options) {
    super(options);

    /**
     * Map from key name to integer ID. Used in encoding only.
     * @member {object.<string,number>}
     * @private
     */
    this.k2i = {};

    /**
     * List of known keys when the handler is constructed. Used in
     * encoding and decoding.
     * @member {string[]}
     * @private
     */
    this.i2k = [];

    if (this.options.keys)
      this.options.keys.forEach(k => {
        this.k2i[k] = this.i2k.length;
        this.i2k.push(k);
      });

    /**
     * List of keys added during encoding because they were not found
     * in i2k. Used in encoding and decoding.
     * @member {string[]}
     * @private
     */
    this.i2k_added = undefined;
  }

  /**
   * @override
   * @instance
   * @memberof TypeMapHandler
   */
  startEncoding(encoder) {
    super.startEncoding(encoder);
    this.i2k_added = [];
  }

  /**
   * @override
   * @instance
   * @memberof KeyDictionaryHandler
   */
  finishEncoding(encoder) {
    super.finishEncoding(encoder);
    encoder.writeTag(CBOR_KEY_MAP);
    encoder.encodeItem(this.i2k_added);
    this.i2k_added = [];
  }

  /**
   * @override
   * @instance
   * @memberof TypeMapHandler
   */
  startDecoding(decoder) {
    super.startDecoding(decoder);
    this.i2k_added = [];
  }

  /**
   * @override
   * @instance
   * @memberof KeyDictionaryHandler
   */
  finishDecoding(decoder, data) {
    data = super.finishDecoding(decoder, data);
    let extras = [];
    if (this.i2k_added)
      // A dictionary was found during tag processing
      extras = this.i2k_added;
    else {
      // If i2k_added is undefined, that means no dictionary was found during
      // tag processing, so it must have been been generated by old code
      // that put the key dict at the end of the data.
      decoder.debug("finishDecoding: no i2k_added found, compatibility");
      // Some early versions of this module generated output with no
      // key dict, which would result in a throw, so handle that with
      // a try-catch.
      try {
        extras = decoder.decodeItem();
        decoder.debug("KDH.finishDecoding old format; read",
                      this.extras.length, " added keys");
      } catch (e) {
        decoder.debug("KDH throw while decoding old format", e);
      }
    }
    remapKeys(data, [ ...this.i2k, ...extras ] );
    return data;
  }

  /**
   * @override
   * @instance
   * @memberof KeyDictionaryHandler
   */
  encodeKey(key, encoder) {
    if (typeof super.encodeKey(key, this) === "undefined") {
      /* istanbul ignore if */
      encoder.debug(`\tKDh ignore ${key}`);
      return undefined;
    }
    if (!this.i2k)
      return key;
    let id = this.k2i[key];
    if (typeof id === "undefined") {
      // It might seem tempting to compare the encoding length of the
      // id against the raw key length, but it rarely improves the
      // data volume enough to make the complexity worthwhile.
      this.k2i[key] = id = this.i2k.length + this.i2k_added.length;
      if (this.options.added)
        this.options.added(key, id);
      this.i2k_added.push(key);
    }
    return id;
  }

  /**
   * @override
   * @instance
   * @memberof KeyDictionaryHandler
   */
  decodeKey(id, decoder) {
    if (id < this.i2k.length)
      return this.i2k[id];
    // else id is not in the supplied key index.

    // The dictionary for supplemental keys will be read at the end
    // of the input data, in finishedDecoding. For now, we insert a
    // placeholder key that will be resolved at the end of decoding,
    // when we have unpacked the dictionary.
    // SMELL: there's a vanishingly small risk that this might
    // duplicate a "real" key.
    const key = `${SECRET}${id}`;
    decoder.debug("inserted placeholder for",id);
    return key;
  }
  
  /**
   * @override
   * @instance
   * @memberof TypeMapHandler
   */
  decode(tag, decoder) {
    if (tag === CBOR_KEY_MAP) {
      // Earlier versions of the code generated the key map directly
      // at the end of the stream. However there was no clear
      // indication of the order in which such items needed to be
      // decoded - it would depend on the order of the handler
      // mixins. It's cleaner and more robust to handle it with a tag
      // - though that does mean we have to keep reading beyond the
      // end of the first object in the stream in the decoder.
      this.i2k_added = decoder.decodeItem();
      decoder.debug("Decoded key map", this.i2k_added);
      // Return `this` so the Decoder doesn't try to read the
      // following item that we already decoded.
      return this;
    }
    return super.decode(tag, decoder);
  }
};

export default KeyDictionaryHandler;
