/*Copyright (C) 2022 Crawford Currie http://c-dot.co.uk*/
/* eslint-disable no-unused-vars */

/**
 * Base class for tag handler objects passed to CBOR for encode/decode.
 * During encoding, the tag handler's `encode()` method is called on every
 * key-value object. The encode method can decide whether to generate
 * a tag to indicate special semantics for the object, or even replace
 * it completely.
 *
 * See the [CBOR specification](https://www.rfc-editor.org/rfc/rfc8949.html)
 * for information about tagging.
 *
 * The actual tag handler implementation used is determined by mixing in
 * specific functionality to this object. Examples of usage are given in
 * the README at the root of this package.
 */
class TagHandler {

  constructor(options = {}) {
    this.options = options;
  }

  /**
   * If the object needs to be tagged, implementations will call
   * {@linkcode Encoder.writeTag} which will inject a tag into
   * the encoded data stream. The tag can be followed with calls to
   * {@linkcode Encoder.encodeItem} though care must be taken not
   * to cause an infinite loop by calling it on `value`.
   * If the value is not tagged, or you want to apply standard CBOR
   * encoding to the object, then return the object. Otherwise if the
   * object is fully encoded by the tagger, return undefined.
   * @param {object} value object that may need to be tagged
   * @param {Encoder} encoder the encoder that is doing the encoding.
   * @return {object} object that needs to be serialised after this
   * tag has been processed, or undefined if sufficient has been
   * written by the tag handler to fully encode the value.
   */
  encode(value, encoder) { return value; }

  /**
   * Decode a tag. The decoding of the tag and it's data must exactly
   * mirror the encoding.
   * @param {number} tag the tag ID.
   * @param {Decoder} decoder the decoder invoking the tagger.
   * @return {object?} return the thawed object, or undefined if the
   * following data was not consumed by the tag handler. If undefined is
   * returned, the Decoder will try to decodeItem the following data - which
   * is fine unless you want to keep that data in the handler.
   */
  decode(tag, decoder) { return undefined; }

  /**
   * Called by {@linkcode Encoder} at the start of encoding.
   * @param {Encoder} encoder the encoder
   */
  startEncoding(encoder) {}

  /**
   * Called by {@linkcode Encoder} at the end of encoding.
   * @param {Encoder} encoder the encoder
   */
  finishEncoding(encoder) {}

  /**
   * Called by {@linkcode Decoder} at the start of decoding.
   * @param {Decoder} encoder the decoder
   */
  startDecoding(encoder) {}

  /**
   * Called by {@linkcode Decoder} at the end of decoding.
   * @param {Decoder} decoder the decoder
   * @param {object} data the decoded data
   * @return {object} the data after any post-decoding cleanup
   */
  finishDecoding(encoder, data) { return data; }

  /**
   * When reading from a stream, there may be tags that apply to
   * the object that follows. So we make the tag handler
   * responsibile for creating arrays.
   * @param {Decoder} decoder the calling decoder
   * @return {Array} a new array
   */
  createArray(decoder) { return []; }

  /**
   * When reading from a stream, there may be tags that apply to
   * the object that follows. So we make the tag handler
   * responsibile for creating basic objects.
   * @param {Decoder} decoder the calling decoder
   * @param {object?} proto the prototype of the new object
   * @return {object} a new simple object
   */
  createObject(decoder, proto) {
    if (proto) {
      let obj = Object.create(proto);
      decoder.debug("Instantiating", proto, "->", obj);
      return obj;
    }
    return {};
  }

  /**
   * Optionally map a key to a more compact representation. Implementations
   * must call superclass and abort if it returns undefined.
   * @param {string} key the key to encode
   * @param {Encoder} encoder the encoder
   * @return {object} a unique identifier for the key, or `undefined` if
   * you want the key to be skipped. By default, the base class will skip
   * all keys that start with '_' to avoid encoding temporary objects.
   */
  encodeKey(key, encoder) {
    if (/^_/.test(key))
      return undefined;
    return key;
  }

  /**
   * Map a compact key representation to the full key. Note that
   * superclass may not be invoked.
   * @param {object} id key identifier, as generated by `encodeKey`
   * @param {Decoder} decoder the calling decoder
   * @return {string} the actual key
   */
  decodeKey(id, decoder) { return id; }
}

export default TagHandler;
